# Generated by Django 2.2.6 on 2022-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220517_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Справка группы', max_length=200, verbose_name='Название группы'),
        ),
    ]
